### ISSUE TITLE
Data format: convert child nodes to array?

### ISSUE THREAD

**Issue by jstcki** [tpreusse/open-budget#1]
The data would be simpler to process (e.g. when using d3.js) if child nodes were stored in regular  instead of associative arrays. Maybe even use a consistent, general key like `children`?

``` json
{
    "type": "budget",
    "children": [
      {
        "id": "1000",
        "type": "directorate",
        "children": [ 
          {
            "id": "010",
            "type": "agency",
            "children": [...]
          },
          ...
        ]
      }, 
    ...]
}

```

Also, keys should probably be camelCased to make it more JavaScript-y (see http://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).

**Comment by tpreusse** [comment]
thanks for your feedback

+1 currently something that evolved organically and inconsistently (e.g. cache is using arrays and a general key).
